### ISSUE TITLE
Does multishot work with other items now?

### ISSUE THREAD

**Issue by HyperSoop** [OffsetMonkey538/Random-Minecraft-Ideas#3]
It's be nice to have it on bows, or dare i say it snowballs/eggs/ender pearls/potions-

**Comment by OffsetMonkey538** [comment]
Thanks for the awesome ideas! I can try, it can't be *that* hard right? Should just be copy pasting some code. I do think that if I do get this working, I should rename the mod to "Better Multishot" because then it's more than just multiple levels of multishot.
I will make a new branch and a pull request for it and if there are any more suggestions, people can talk about it there
